### ISSUE TITLE
Please describe how to get rid of W/Datadog: tag "version:4.1.4 beta" was modified to "version:4.1.4_beta" to match our constraints.

### ISSUE THREAD

**Issue by nordfalk** [DataDog/dd-sdk-android#1018]
Please describe if there is no way to get rid of
```
W/Datadog: tag "version:4.1.4 beta" was modified to "version:4.1.4_beta" to match our constraints.
```

Currently I get this warning constantly if I have a space in my app version name, like

```
android {
    productFlavors {
        stage {
            versionName "version:4.1.4 beta"
```

I have tried
```
datadog {
    versionName = "version:4.1.4_beta"
```
but it didnt help.

I have also tried
```
            logger = Logger.Builder()
                .build()
            logger.addTag("version", "version:4.1.4_beta")
```
but it also didnt help.

I understand that 'version' is a reserved tag (https://docs.datadoghq.com/getting_started/tagging/), and that  reserved tags cannot be changed, but its really crazy that there is no way to set it manually. 

It prohibits the use of space and other characters in the user facing app version name.

Please provide some means setting version name so I can start using a user friendly app version name again.

**Comment by 0xnm** [comment]
Hello @nordfalk! Indeed `version` is a reserved tag and we currently read it from the manifest and not giving user the ability to set it by any other means.

When you are using `logger.addTag("version", "version:4.1.4_beta")`, whatever you provide is ignored, because `version` is set by the SDK internally.

When you are using `datadog` configuration extension in the Gradle configuration script, it is responsible only for the Datadog Gradle Plugin configuration which sets the metadata for the mapping file upload, but doesn't set any values used in the runtime.

So as you've seen in the docs page tag values should follow the conventions in terms of the possible characters.

While we may consider giving a flexibility on the SDK side to set a custom version, can you please help us to understand the importance/need of such change: do you show this version name in the app to the user directly?

**Comment by nordfalk** [comment]
According to the docs https://developer.android.com/guide/topics/manifest/manifest-element#vname it can be any string, and has no other purpose than to be displayed to users.

Here are some version names we use for beta builds (internal and public)

![image](https://user-images.githubusercontent.com/1143272/186170177-336974ea-85fc-4d82-be92-fb435fec3159.png)
![image](https://user-images.githubusercontent.com/1143272/186172566-c27b5030-8430-45dd-bd0d-4683da3a2c68.png)

Google Play is showing the version name (public beta testers see some of the above names with spaces)
![image](https://user-images.githubusercontent.com/1143272/186173197-50452c12-4605-455a-923b-18d8a135d9ff.png)


About-screen in the app is showing the version name
![image](https://user-images.githubusercontent.com/1143272/186170333-a5986718-1745-47c0-b94e-83e43dcbd3cb.png)

**Comment by 0xnm** [comment]
It seems that impact of this is quite minor. I understand that this warning may be annoying, but tag value format constraint cannot be lifted (we may consider however to lower message level from warning to info).

**Comment by mayardb** [comment]
Hello,

I have the same kind of polluting issue:
tag "version:3.6.1-12-g2aa9e83-DEBUG" was modified to "version:3.6.1-12-g2aa9e83-debug" to match our constraints. (happening every time I log something)

Could you just store it once in the right format ?

In `CoreFeature`, you get `packageVersion` from the `packageManager`:
```
packageVersion = appContext.packageManager.getPackageInfo(packageName, 0).let {
    it.versionName ?: it.versionCode.toString()
}
``` 

Then in `LogGenerator`, maybe you could just format the `appVersionTag` accordingly to your constraints.

```
 private val appVersionTag = if (appVersion.isNotEmpty()) {
     "${LogAttributes.APPLICATION_VERSION}:$appVersion"
} else {
    null
}
```

**Comment by kirillzh** [comment]
@0xnm, any chance this can be revisited and addressed?


Our app is using version name format like this `2024.59.0 (1)`, and the Datadog SDK is spamming our logs multiples times per second because of this issue:

```
[_dd.sdk_core.default]: tag "version:2024.59.0 (1)" was modified to "version:2024.59.0__1_" to match our constraints.
```

<img width="1226" alt="Screenshot 2024-05-01 at 9 48 45 AM" src="https://github.com/DataDog/dd-sdk-android/assets/5660531/c06f9735-7517-4123-85c3-352e59f79e30">

**Comment by 0xnm** [comment]
Hello @kirillzh!

Thanks for bringing up this old topic. Indeed, we can currently improve this a bit by logging such message only once.

The necessary change is done in the [2.9.0 release](https://github.com/DataDog/dd-sdk-android/releases/tag/2.9.0).

Regarding the relaxing of the format constraints, as I said, it is not possible, because it is a limitation of the Datadog system.
