### ISSUE TITLE
com.datadog.android.log.Logger accepts only typed attributes 

### ISSUE THREAD

**Issue by arnoldasjasiunas** [DataDog/dd-sdk-android#1240]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
using library dd-sdk-android:1.14.1

**Is your feature request related to a problem? Please describe.**
I don't see the use for ensuring certain types when adding attributes to Logger.

When adding attributes to Logger.addAttribute(key: String, value: X) I have to adhere to allowed types like primitives (Boolean, Integer) or Json types.
What is the reason for this? Looking into the datadog codebase deeper, I see if a values type is not accounted for in  when converting `LogEvent.toJson()` in `Any?.toJsonElement()` extension in else clause any other type is plainly converted to string:
`JsonPrimitive(toString()) `

**Describe the solution you'd like**
convert Logger.addAttribute methods to a single addAtribute(key: String, value: Any?)

**Comment by 0xnm** [comment]
Hello @arnoldasjasiunas! Thanks for your request, indeed it would be possible to do. We will add this improvement into our backlog.

**Comment by 0xnm** [comment]
Hello @arnoldasjasiunas!

We now have [first beta of SDK v2 available](https://github.com/DataDog/dd-sdk-android/releases/tag/2.0.0-beta1) which supports `Any?` type as an argument of `Logger.addAtribute` call. Please check migration guide for more details.

Feel free to re-open this ticket if your issue is not solved.
