### ISSUE TITLE
Duplicate class androidx.work.OneTimeWorkRequestKt build error when using with AirWatch

### ISSUE THREAD

**Issue by distinctdan** [DataDog/dd-sdk-android#1616]
I'm trying to use the DD logging package, but I'm getting build errors from a duplicate transitive dependency that's conflicting with AirWatch. I've tried forcing the work version to `2.8.1`, but that didn't work. I'm currently trying to exclude it from AirWatch, but that's not working either and is failing with the same error. Any ideas on how to get AirWatch and DD to work together? 

```
Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)
Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)
```

build.gradle:
```gradle
    implementation('com.airwatch.android:AirWatchSDK:23.07') {
        // Airwatch depends on an old version of kotlinx serialization, which conflicts with
        // us using the modern version because Gradle only allows a single version to be loaded.
        exclude group: 'org.jetbrains.kotlinx', module: 'kotlinx-serialization-runtime'
        // Conflict with datadog
        exclude group: 'androidx.work', module: 'work-runtime'
    }
    implementation('com.airwatch.android:AWFramework:23.07') {
        exclude group: 'org.jetbrains.kotlinx', module: 'kotlinx-serialization-runtime'
        // Conflict with datadog
        exclude group: 'androidx.work', module: 'work-runtime'
    }
    implementation("com.airwatch.android:AWNetworkLibrary:23.07") {
        exclude group: 'org.jetbrains.kotlinx', module: 'kotlinx-serialization-runtime'
        // Conflict with datadog
        exclude group: 'androidx.work', module: 'work-runtime'
    }
    implementation "com.datadoghq:dd-sdk-android-logs:2.1.0"
```

**Additional context**
 - Datadog SDK version: 2.1.0
 - Versions of any other relevant dependencies AirWatch: 23.07
 - Gradle Plugins:
```
plugins {
    id 'com.android.application' version '8.1.0' apply false
    id 'com.android.library' version '8.1.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.21' apply false
    id 'com.google.dagger.hilt.android' version '2.46.1' apply false
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.8.21' apply false
}
```

**Comment by georgeBanno** [comment]
I'm seeing the same issue except just on a regular app.  Tried excluding but then the app could load work manager.
```Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)
Caused by: java.lang.RuntimeException: Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)```

**Comment by 0xnm** [comment]
Hello @distinctdan!

I don't have an access to AirWatch SDK (it is proprietary SDK, which is not distributed publicly), so I cannot test for the solution, but maybe I can give some useful hints.

The reason you see this error is because according to the [following change](https://android-review.googlesource.com/c/platform/frameworks/support/+/2052910) some classes were moved from `work-runtime-ktx` artifact to `work-runtime` module in version 2.8 in comparison with version 2.7 (full changelog is [here](https://developer.android.com/jetpack/androidx/releases/work#version_28_2)).

This means that you can do the following:

* Try to exclude `work-runtime-ktx` module (in your listing you are excluding `work-runtime` module, which won't help). There is a risk though that some code is still using this module.
* Try to force use `work-runtime-ktx` version 2.8 instead of 2.7 (this module still exists according to the [following page](https://maven.google.com/web/index.html#androidx.work:work-runtime-ktx)). You can read more information about dependency resolution management [here](https://docs.gradle.org/current/userguide/resolution_rules.html).

You can also always check what are the versions of libraries are used in your compile configuration by running `dependencies` task on the module under the question.

@georgeBanno I think that my advices above should work for you as well.

**Comment by georgeBanno** [comment]
> Hello @distinctdan!
> 
> I don't have an access to AirWatch SDK (it is proprietary SDK, which is not distributed publicly), so I cannot test for the solution, but maybe I can give some useful hints.
> 
> The reason you see this error is because according to the [following change](https://android-review.googlesource.com/c/platform/frameworks/support/+/2052910) some classes were moved from `work-runtime-ktx` artifact to `work-runtime` module in version 2.8 in comparison with version 2.7 (full changelog is [here](https://developer.android.com/jetpack/androidx/releases/work#version_28_2)).
> 
> This means that you can do the following:
> 
> * Try to exclude `work-runtime-ktx` module (in your listing you are excluding `work-runtime` module, which won't help). There is a risk though that some code is still using this module.
> * Try to force use `work-runtime-ktx` version 2.8 instead of 2.7 (this module still exists according to the [following page](https://maven.google.com/web/index.html#androidx.work:work-runtime-ktx)). You can read more information about dependency resolution management [here](https://docs.gradle.org/current/userguide/resolution_rules.html).
> 
> You can also always check what are the versions of libraries are used in your compile configuration by running `dependencies` task on the module under the question.
> 
> @georgeBanno I think that my advices above should work for you as well.

Thanks @0xnm .  I meant to post sooner but I actually worked it out similar to what you suggested.  I had to migrate our app to support 2.8.1 of -ktx . However so that others are aware we are using Room for our Database and because of dependencies in -ktx 2.8.1 I also had to update room and modify a bit of our Database code.
