### ISSUE TITLE
Was the latest version published to maven?

### ISSUE THREAD

**Issue by jamesbluecrow** [DataDog/dd-sdk-android#1628]
**Describe what happened**
It seems there may be a problem with the release publishing to maven.

I see this error `Failed to resolve: com.datadoghq:dd-sdk-android:2.1.0` when I try to update to the latest version, `com.datadoghq:dd-sdk-android:1.19.3` works fine on the other hand.

**Steps to reproduce the issue:**
Update the dependency version to `com.datadoghq:dd-sdk-android:2.1.0`.

**Describe what you expected:**
The dependency is resolved.

**Comment by xgouchet** [comment]
Hi @jamesbluecrow, when we upgraded from `1.x` to `2.x`, there was a shift in our architecture, the main one being that we split the SDK in several independent modules. From version `2.0.0` onward, the module `com.datadoghq:dd-sdk-android` doesn't exist anymore, which is why you can't find it in Maven. 

You can follow our [Migration Guide](https://github.com/DataDog/dd-sdk-android/blob/develop/MIGRATION.MD) to learn how to upgrade from `1.x` to `2.x`.
