### ISSUE TITLE
Events are not send to data dog

### ISSUE THREAD

**Issue by igorwojda** [DataDog/dd-sdk-android#1749]
Thanks for taking the time for reporting an issue!

**Describe what happened**

Events are not send to data dog when modifying creating map copy via `event.copy()` method inside `map`

**Steps to reproduce the issue:**
```kotlin
val logEventMapper = object: EventMapper<LogEvent> {
            override fun map(event: LogEvent): LogEvent {
                return event.copy()
            }
        }

val logsConfig = LogsConfiguration
            .Builder()
            .setEventMapper(logEventMapper)
            .build()
```

**Describe what you expected:**

Event are send correctly

**Additional context**
 - Android OS version: 13
 - Device Model: Samsung SM-G991W
 - Datadog SDK version: 2.3.0
 - Versions of any other relevant dependencies (OkHttp, …):  x
 - Proguard configuration: Debug build
 - Gradle Plugins: None: apg, kotlin-gradle-plugin, kotlin-serialization

**Comment by xgouchet** [comment]
Hi @igorwojda and thanks for opening this question, 

this is working as intended, as mentioned in the EventMapper's [javadoc](https://github.com/DataDog/dd-sdk-android/blob/ffd837e979a1bbbf702e974f95346ac861410c00/dd-sdk-android-core/src/main/kotlin/com/datadog/android/event/EventMapper.kt). 

We have a check in place to ensure the event mapper returns the same instance of the event it receives. This is to ensure that all the internal fields marked as non mutable are indeed preserved by the event mapper implementation. You don't need to make a copy as all the fields that are allowed to be modified are mutable in the event object.

**Comment by igorwojda** [comment]
This is an unintuitive behaviour. Also silent fail makes this quite concerning.

Ideal solution would be not to use mutable fields, but you should at least consider throwing an exception.

**Comment by xgouchet** [comment]
> Also silent fail makes this quite concerning.

This behavior is not silent if you enable the SDK internal logs : 
```
Datadog.setVerbosity(Log.VERBOSE)
```
Would print a warning log in the logcat saying: 
"RumEventMapper: the returned mapped object was not the  same instance as the original object. This event will be dropped: { …}"

> Ideal solution would be not to use mutable fields

Again, because we need to ensure that only some specific fields would change via the mapper, we can't allow any copy. Doing that would mean making complex nested comparison between the original and updated event, which would degrade the performance of the host application.
Making the relevant fields mutable, as stated in the docs, let customers map the fields effortlessly by replacing the mutable fields.

> but you should at least consider throwing an exception.

Our policy is to never throw exceptions in our SDK, as we don't want to inadvertently crash the host application on the end user's device.

**Comment by igorwojda** [comment]
I got the idea behind, not failing the app, although this behaviour could be more strict in `debug` build by default (or at least there should be a way to enable strict verification).

**Comment by igorwojda** [comment]
@xgouchet So what is the correct way of adding these properties?
