### ISSUE TITLE
App build failed with the 1.4.1:beta3 dependency

### ISSUE THREAD

**Issue by mathuadi3** [DataDog/dd-sdk-android#642]
Thanks for taking the time for reporting an issue!

**Describe what happened**

```
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDevDebug'.
> Could not resolve all files for configuration ':app:devDebugCompileClasspath'.
   > Could not find com.datadoghq:dd-sdk-android:1.4.0-beta3.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Steps to reproduce the issue:**

Here is my build.gradle(app):::
`
    implementation "com.datadoghq:dd-sdk-android:1.4.0-beta3"

`

The build fails after adding this dependency. Unable to proceed.
**Describe what you expected:**
Do i need to add any other dependency or what?
**Additional context**

 - Datadog SDK version: 1.4.0-beta3
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration:

**Comment by 0xnm** [comment]
Hello @mathuadi3! Please update DataDog SDK version to at least `1.8.1` (latest version is `1.9.1`). Starting from this version we host our artifacts on Maven Central instead of Bintray for older artifacts. Even though JFrog claimed that they are going to keep JCenter in read-only mode https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/, it seems it is not the case.
