### ISSUE TITLE
Bad Gateway on librairies used by Datadog

### ISSUE THREAD

**Issue by yanncheckandvisit** [DataDog/dd-sdk-android#660]
Thanks for taking the time for reporting an issue!

**Describe what happened**
When i build my application i get an error saying that the libraries used by the sdk are not downloadable.

```
A problem occurred configuring root project 'project'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve net.sf.proguard:proguard-base:6.0.3.
     Required by:
         project : > com.android.tools.build:gradle:4.1.3 > net.sf.proguard:proguard-gradle:6.0.3
      > Could not resolve net.sf.proguard:proguard-base:6.0.3.
         > Could not get resource 'https://dl.bintray.com/datadog/datadog-maven/net/sf/proguard/proguard-base/6.0.3/proguard-base-6.0.3.pom'.
            > Could not HEAD 'https://dl.bintray.com/datadog/datadog-maven/net/sf/proguard/proguard-base/6.0.3/proguard-base-6.0.3.pom'. Received status code 502 from server: Bad Gateway
```

**Steps to reproduce the issue:**
Build your app with the Datadog SDK.

**Describe what you expected:**
A cleaned build :) 

**Additional context**
 - Android OS version:
 - Device Model:
 - Datadog SDK version:
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins:

**Comment by 0xnm** [comment]
Hello @yanncheckandvisit. Our SDK doesn't use `proguard-base` library. The issue probably happens because you have old Datadog Bintray maven repo in the configuration and Gradle queries all the repositories to search for the library.

As you may know, Bintray is discontinued now and we have SDKs starting from version `1.8.1` on [Maven Central](https://search.maven.org/artifact/com.datadoghq/dd-sdk-android) instead.

I would advise to remove Datadog Bintray repo from your configuration and use latest SDK available on Maven Central.

You can also check [setup docs](https://docs.datadoghq.com/real_user_monitoring/android/?tab=us#setup).

**Comment by yanncheckandvisit** [comment]
Ok you're right. But you shoud update your documentation in French. Cause I'm on 1.9.0 and the documentation says to add  

```
repositories {
    maven { url "https://dl.bintray.com/datadog/datadog-maven" }
}

dependencies {
    implementation "com.datadoghq:dd-sdk-android:x.x.x"
}
```

Thanks

**Comment by 0xnm** [comment]
Can you please give a link to the page you are referencing to?

**Comment by yanncheckandvisit** [comment]
Here -> https://docs.datadoghq.com/fr/logs/log_collection/android/?tab=siteamricain

**Comment by 0xnm** [comment]
Indeed, French page is outdated, thanks for reporting it.
