### ISSUE TITLE
RUM de-obfuscated doesn't work

### ISSUE THREAD

**Issue by MohammadRezaei92** [DataDog/dd-sdk-android#722]
Based on pipeline logs the mapping file uploaded successfully but, in datadaog RUM dashboard logs are still obfuscated

**Describe what you expected:**

**Additional context**
 - Android OS version: 11
 - Device Model: Samsung SM-G991B
 - Datadog SDK version:1.10.0
 - Versions of any other relevant dependencies (OkHttp, …): 4.9.1
 - Proguard configuration: 
 - Gradle Plugins:
 apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

apply plugin: "androidx.navigation.safeargs"

apply plugin: 'com.google.gms.google-services'

apply plugin: 'com.google.firebase.crashlytics'

apply plugin: 'com.google.firebase.firebase-perf'

**Comment by xgouchet** [comment]
Hi @MohammadRezaei92, I'm not seeing logs as obfuscated in your screenshot. But anyway, can you confirm that the variant reported in the upload logs does match your application's variant in the reported errors? Can you please open a [Support ticket](https://www.datadoghq.com/support/) so that we can look into this issue?

**Comment by xgouchet** [comment]
Oh, by the way it seems the version the upload reported is `1.10.321`, but the one in the error page is `1.10.321-beta`. This might be the cause of your issue, as the version name must be identical in both the uploaded mapping files and the application errors.
