### ISSUE TITLE
Error: Application Not Responding

### ISSUE THREAD

**Issue by tudoaneverfit** [DataDog/dd-sdk-android#725]
**Describe what happened**
My customer met an issue about freezing app when he using app
I checked log on DataDog and meet this log:
 "com.datadog.android.rum.internal.anr.ANRException: Application Not Responding"
**Describe what you expected:**
Can you help me know that Why does this issue happened?
**Additional context**
 - Android OS version: 11
 - Device Model: Samsung SM-N986U
 - Datadog SDK version: com.datadoghq:dd-sdk-android:1.10.0-rc1
 - Versions of any other relevant dependencies (OkHttp, …): com.squareup.okhttp3:logging-interceptor:3.8.0, retrofit: 2.3.0
 - Gradle Plugins: 1.4.32

**Comment by xgouchet** [comment]
Hi @tudoaneverfit, an ANR ussually happens when your application performs work in the foreground. [This page](https://developer.android.com/topic/performance/vitals/anr) explains in details what can cause the app to freeze, and how to avoid that. In theory, the error you see in Datadog contains a stack trace showing what the blocking thread is performing when the ANR was detected, which should give pointers on which part of your app is involved.
