### ISSUE TITLE
Facing ANR due to VitalFrameCallback

### ISSUE THREAD

**Issue by Meenu1401** [DataDog/dd-sdk-android#889]
@xgouchet Facing ANR due to DataDog. Please resolve this. 

**SDK version**: 1.10.0
**Android OS version** : 11
**Device** : realme narzo 50A

<img width="1261" alt="Screenshot 2022-04-04 at 12 13 05 PM" src="https://user-images.githubusercontent.com/14975590/161487690-a15010aa-480a-4917-8ce3-fcdabed55802.png">

_Originally posted by @Meenu1401 in https://github.com/DataDog/dd-sdk-android/issues/455#issuecomment-1087177011_

**Comment by xgouchet** [comment]
Thanks @Meenu1401 for reporting this issue, we're going to investigate this issue. Do you know how often this ANR occur, and any info on what types of devices are impacted?

As I mentionned on your original post, although our SDK do appear to be in this stack, we're calling a method that shouldn't be blocking. The root cause of the ANR seems to be deeper, in the Android Framework, as something might be blocking the vertical sync of the display, hence causing an ANR. As such I'm not sure if there's something we can do to prevent this.

**Comment by xgouchet** [comment]
Hi @Meenu1401, were you able to get more information on when and how this ANR occur? We aren't able to reproduce this, and without more information we won't be able to treat this issue.

**Comment by xgouchet** [comment]
This issue has been stale for a long time, so we're closing it. Feel free to reopen with more information if need be.
