### ISSUE TITLE
[Bug] datadog.android.rum.tracking.ActivityViewTrackingStrategy.onActivityResumed crash

### ISSUE THREAD

**Issue by methob** [DataDog/dd-sdk-android#904]
i'm getting this error:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {mypackage/o.setVerticalOffset}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Parcel.dataSize()' on a null object reference

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Parcel.dataSize()' on a null object reference 
  at android.os.BaseBundle.(BaseBundle.java:164) 
  at android.os.Bundle.(Bundle.java:106) 
  at android.content.Intent.getExtras(Intent.java:6622) 
  at com.datadog.android.rum.tracking.ActivityViewTrackingStrategy.onActivityResumed(ActivityViewTrackingStrategy.java:56) 
  at com.datadog.android.rum.tracking.MixedViewTrackingStrategy.onActivityResumed(MixedViewTrackingStrategy.java:71) 
  at android.app.Application.dispatchActivityResumed(Application.java:219) 
  at android.app.Activity.onResume(Activity.java:1264) 
  at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:434)
```

in my project we use dexguard

```
mapping file line: mypackage.presentation.HomeCardsChartAdapter -> o.setVerticalOffset:
```

## Steps to reproduce the issue:

I don't know how to reproduce it, it's a recurring error that occurs with few users on some devices

## Additional context

Android OS version: Android 5,6,7
Device Model: Galaxy J5, LG K11
Datadog SDK version: 1.11.0

**Comment by xgouchet** [comment]
Hi @methob, and thanks for reporting this issue. At first glance it seems like an exception that might occur within the Android internals (when the `BaseBundle` constructor tries to access the `mParcelledData` field of a `Bundle` to copy. 

Without  any steps to reproduce this issue I'm not sure there's a lot we can do here. Do you have any information about what `extras` might be passed into the Activity Intent?  Please let us know if you have more information about this so that we can investigate on our end.

**Comment by methob** [comment]
I can't say for sure what's in the intent, but I send a string called "redirect" 
and a flag FLAG_ACTIVITY_NEW_TASK 
this only happens with android 5,6,7
and with old devices

**Comment by xgouchet** [comment]
There was no answer for a month now, we'll close this issue but feel free to open it again if you have more information to reproduce it.
