### ISSUE TITLE
Configurable minimum battery level

### ISSUE THREAD

**Issue by justinwyer** [DataDog/dd-sdk-android#939]
Currently the SDK does not transmit logs if the battery level of the device is less than 10%, I would like to contribute a PR that would make 10% the default but allow overriding this setting. Would DataDog be open to this?

**Comment by xgouchet** [comment]
Hi @justinwyer, 

that's something I am not confortable doing. This check is there for a specific reason: playing nice with the end user's device and ensuring Datadog doesn't degrade their experience, even when the tracked application is in background. Even though the events are not sent immediately, we still track the user's journey when the battery is low, and the events will be sent eventually (which is a similar behavior to what happens when the user is offline).

Is there a specific use case that you're trying to solve with this, or is it just a question of getting the data "faster"?

**Comment by justinwyer** [comment]
Thanks so much for the reply @xgouchet 

We have mains powered Android phones as part of our IoT project and currently they run down to 2% as far as the OS is concerned, so we never get the logs unless the phone is restarted. I completely understand why you have the check however and why you might be hesitant to allow it to be overridden.

In this case I might try get the whole SDK building locally and create my own release as I'd prefer to use DD.

**Comment by xgouchet** [comment]
> We have mains powered Android phones as part of our IoT project 

Does this issue still occur with our `1.13.0-rc1` SDK. We made a [change recently](https://github.com/DataDog/dd-sdk-android/pull/858) to take into account devices that are always plugged in (e.g.: Android TV devices), so it might work for your IoT devices as well. If not, could you take a look in the [BroadcastReceiverSystemInfoProvider](https://github.com/DataDog/dd-sdk-android/blob/develop/dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt) to see if there's an extra information that is passed on your device that can be used to know that they do have enough power (even if they report 2% battery).

**Comment by justinwyer** [comment]
Thanks! Let me have a look and see.

**Comment by justinwyer** [comment]
Unfortunately with out hardware setup the device just thinks the battery is infinitely recharging, we may be able to fix it in a future revision. For now a custom build is working fine so we will stick to that.
