### ISSUE TITLE
Errors not shown in Error Tracking depending on the method used

### ISSUE THREAD

**Issue by ivan-hernandez-scopely** [DataDog/dd-sdk-android#959]
**Describe what happened**

-  Using those `RumMonitor` calls i would expect for each error to have a new issue or link it to an existing issue:
    - fun `stopResourceWithError(String,` Int?, String, RumErrorSource, Throwable, Map<String, Any?> = emptyMap())
    - fun `stopResourceWithError`(String, Int?, String, RumErrorSource, String, String?, Map<String, Any?> = emptyMap())
    - fun `addError`(String, RumErrorSource, Throwable?, Map<String, Any?>)
    - fun `addErrorWithStacktrace`(String, RumErrorSource, String?, Map<String, Any?>)
  - But actually only one of those works as expected:
    - `addError`, but only if add the `stacktrace` in the `Throwable` and use `RumErrorSouce.SOURCE`
    - `GlobalRum.get().addError(message, RumErrorSource.SOURCE, new Throwable(message, new Throwable(stackTrace)), customAttributes);`
    - stopResourceWithError + Throwable also reports the issue for the error (also only if use `RumErrorSouce.SOURCE` and Throwable(stacktrace) , but it does not let me setup the `RumAttributes.INTERNAL_ERROR_TYPE` like in `addError` .
    - And yet another issue. Triggering a crash. I see the error but this error (is_crash true) is not shown also in the Error Tracking.

**Steps to reproduce the issue:**
- Call any of those methods.

**Describe what you expected:**
- I would expect that any of those calls aside from showing an error on my view also add an issue to be able to check those errors in the Error Tracking.
- Also i would expect that errors with the same stacktrace but different messages to be logged as different issues...

**Additional context**
 - Android OS version: 12
 - Device Model: OnePlus 8
 - Datadog SDK version: 1.12.0
 - **Calling java api from c# (using unity)**

**Comment by xgouchet** [comment]
Hi @ivan-hernandez-scopely , and thanks for opening this ticket. 

> I would expect that any of those calls aside from showing an error on my view also add an issue to be able to check those errors in the Error Tracking.
That's not a bug but the way our Error Tracking actually is expected to work. Error tracking first needs a Stacktrace to be able to group error instances together, and only works for errors with type `SOURCE`.
By design, stopResourceWithError always adds the type `NETWORK`.

> Triggering a crash. I see the error but this error (is_crash true) is not shown also in the Error Tracking.
When you trigger a crash, the Error should have the `error.is_crash:true` attribute, which you can use to filter errors in the query field. If this doesn't work, please open a [support ticket](https://www.datadoghq.com/support/) as this will be handled by the Error Tracking team.

> Also i would expect that errors with the same stacktrace but different messages to be logged as different issues
In theory the error message is used to group errors together, if this doesn't work, again please open a [support ticket](https://www.datadoghq.com/support/) for the Error Tracking team.

**Comment by ivan-hernandez-scopely** [comment]
> By design, stopResourceWithError always adds the type NETWORK.
This is true in your **iOS** implementation but on **Android** you allow to change the source to source instead of network (check the methods above), which is super nice and i will ask to have it on iOS.

The issue with `stopResourceWithError` for us is that it does not allow us to change the `RumAttributes.INTERNAL_ERROR_TYPE` like `AddError` does (it reads it from the custom attributes).

An the higher issue here is that i would like to avoid using the methods with `Throwables` and be able to work with the `String` `stacktraces` instead.

**Comment by xgouchet** [comment]
In theory sending an error with a java stacktrace should be enough for it to be taken into account. If it doesn't work then contact our support to better understand the issue.
